apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo 
spec:
  selector:
    matchLabels:
      app: java-demo 
  replicas: 2
  progressDeadlineSeconds: 60
  template:
    metadata:
      labels:
        app: java-demo 
    spec:
      containers:
      - name: java-demo 
        image: machamba/java-demo-app:1.2.3
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
