apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo 
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: java-demo 
  replicas: 2
  template:
    metadata:
      labels:
        app: java-demo 
    spec:
      containers:
      - name: java-demo 
        image: machamba/java-demo-app:1.2.1
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
